# In-memory database settings
spring.datasource.url=jdbc:h2:mem:certdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Server port
server.port=8080

# Blockchain configuration - Need to be set after deployment
# blockchain.rpc-url=http://127.0.0.1:7545
# blockchain.private-key=<Your Ganache Private Key>
# blockchain.contract-address=0x55A75a23a8144275FC5F17Ad2C4126e24B6Ae65c
